### PR TITLE
Add Mac OS MIDI device names and force X86 build for compatibility

### PR DESCRIPTION
**Pull request by guilevi**
The device names under Mac OS include the manufacturer at the beginning, so the plugin would not work for A and M series keyboards. This has been fixed. I also forced the build for X86 under Mac OS so that building on Apple Silicon wouldn't generate binaries that were only compatible with the Reaper beta.

### CODE REVIEW

**Comment by MarcoZehe** [comment]
Would it be possible to adapt this so it creates a universal binary, so those of us who own an Apple Silicon Mac can take full advantage of the plugin when running under the REAPER M1 beta?

**Comment by terminar** [comment]
@guilevi sorry for the late answer, I haven't seen the PR until now.
I am not sure if the current strcmp() and #ifdef solution is really a good idea, maybe it should be changed to strstr() which should then work on both platforms without #ifdef. I'll take a look at the patch within this week I think.

> Would it be possible to adapt this so it creates a universal binary, so those of us who own an Apple Silicon Mac can take full advantage of the plugin when running under the REAPER M1 beta?

I took a look at the comments from Justin in the official Reaper forum and it looks like that it's still to early stepping into the M1-ARM situation. He stated that the M1 reaper version works (kind of) and that there seems to be some in-app X86_64 emulation compatibility (for X86_64 plugins running inside ARM-Reaper) but it doesn't support VST3 yet and there are some quirks with the scripting stuff of Reaper. Even he is suggesting to use the Intel version. 
Since X86_64 emulation currently works better than the ARM build I'll suggest to stick with it at the moment. That doesn't mean we shouldn't try it but I don't think that should be released and supported officially by reaKontrol yet.

**Comment by MarcoZehe** [comment]
> I took a look at the comments from Justin in the official Reaper forum and it looks like that it's still to early stepping into the M1-ARM situation. He stated that the M1 reaper version works (kind of) and that there seems to be some in-app X86_64 emulation compatibility (for X86_64 plugins running inside ARM-Reaper) but it doesn't support VST3 yet and there are some quirks with the scripting stuff of Reaper. Even he is suggesting to use the Intel version.


Fair enough.

> Since X86_64 emulation currently works better than the ARM build I'll suggest to stick with it at the moment. That doesn't mean we shouldn't try it but I don't think that should be released and supported officially by reaKontrol yet.

Do we know the situation of the NI products on ARM64? E. G. how do they integrate into, for example, Logic Pro, which has been native ARM since v10.6?

**Comment by terminar** [comment]
> Do we know the situation of the NI products on ARM64? E. G. how do they integrate into, for example, Logic Pro, which has been native ARM since v10.6?

Yes, we do. 
As stated officially by NI they are compatible with Big Sur and M1 in the term of installable via Native Access and running on Rosetta2 (the X86_64 emulation on the M1). Not working: Massive X (and it maybe never will work outside of X86_64 because of a specific use of a x86 processor extension called AVX).

Regarding Logic it seems to be the in-app X86_86 "compatibility" Justin talked about.
I think it's a bigger problem to have a general "Big Sur" compatibility than getting stuff running on Rosetta2...
Still many VSTs are not compatible with Big Sur. Regarding Native Instruments they stated on their support side that also some older hardware is not working on Catalina anymore (or Big Sur? Not sure...).

**Comment by guilevi** [comment]
Thanks so much for taking a look!

Full disclosure: While I did test this for a while before submitting this pull request to make sure I hadn't broken anything, I made this change with absolutely minimal knowledge of the language and everything involved. Given that it was a tiny, seemingly inoffensive change, I shared it anyway. This also explains why I made this force x86-64 instead of making a universal binary, I found out that it was just as easy a bit later. All of this to say that you can feel free to ignore the request and do all of this the proper way if this may eventually cause problems on one platform or another. :)

Thank you!

**Comment by pitermach** [comment]
In regards to how these plugins work in Logic, last I heard if you run logic natively, it will bridge the Komplete plugin with Rosetta, but every instance of the plugin is bridged in a separate process and can't communicate with other KK instances. This means that things like instance switching doesn't work automatically, unless Native fixed this in Logic. If you instead tell Logic as a hole to run with Rosetta, then everything works how it should. So I suspect that even if you had ReaKontrol compiled and working in the ARM Reaper you'd run into similar issues (I think @guilevi saw it behave this way when he built RK as ARM64). Also for the record, running the intel version of Reaper with the patched ReaKontrol works correctly.

**Comment by terminar** [comment]
@guilevi I've taken your branch and added a more general platform-agnostic approach as discussed (https://github.com/brummbrum/reaKontrol/pull/53).
I am waiting for feedback but I think, we will merge the other PR and - if merged - this will be closed.
Due to the fact that my PR is based on your branch/patch you will still have your mark set in the git history (if @brummbrum is OK with that) ;)

**Pull request merged**
