### PR TITLE
OSX port

### PR DESCRIPTION
**Pull request by terminar**
This pull request adds OSX support.

### CODE REVIEW

**Comment by darkone23** [comment]
👍

**Comment by Mturner88** [comment]
This doesn't seem to work when using a portable copy of reaper. I'm using the konplete A61. I've downloaded it using Reapack.

**Comment by antkn33** [comment]
How do you install this? Thanks

**Comment by brummbrum** [comment]
See manual. Easiest way on both OSX as well as Windows is to use ReaPack

**Comment by toughbigman** [comment]
You are awesome. I'm going to give this a try. Thanks!

**Pull request merged**
